#!/bin/bash
#set -x

#---
# Shellscript com a finalidade de criar um container via docker para o uso do software Teamviewer v.11.0.25
# Usado a imagem Ubuntu 14.04
# Esse Shsc é baseado no projeto https://github.com/bbinet/docker-teamviewer
# Referencia da configuração do xorg no docker https://github.com/mviereck/x11docker/wiki/
#---

# Criando diretório para container e o arquivo Dockerfile para criação da imagem
echo 'Criando o diretório do container' ; sleep 2
mkdir -v $HOME/teamv_cont

# Construindo a imagem do container
echo 'Construindo a imagem' ; sleep 2
docker build -t ubu14/teamviewer $HOME/teamv_cont/

# Criando e configurando o arquivo para compartilhar o cookie para de autoridade da sessão do Xorg
echo 'Criando o cookie de autoridade do servidor grafico X'; sleep 2; \
rm -rf /tmp/containercookie; \ 
touch /tmp/containercookie 2> /dev/null; \
Cookiefile=/tmp/containercookie; \
Cookie="$(xauth nlist $DISPLAY | sed -e 's/^..../ffff/')"; \
echo "$Cookie" | xauth -f "$Cookiefile" nmerge -

# Iniciando o container
echo 'Iniciando o container'; sleep 2 
docker run -it -d --name teamviewer --env XAUTHORITY=/cookie -v $Cookiefile:/cookie --env DISPLAY=$DISPLAY -v /tmp/.X11-unix/X0:/tmp/.X11-unix/X0 --ipc=host ubu14/teamviewer; docker container prune -f

# Aguardando a configuração do arquivo global.conf para não precisar aceitar a licença todas as vezes que iniciar o container
echo "Aguardando configuração do arquivo global.conf para aceitar a licença apenas uma vez enviar o novo arquivo para o diretório $HOME/teamv_conf" 
while [ TRUE ];
do 
	unset lic_accep
	lic_accep=$(docker exec teamviewer grep "EulaAccepted = 1" /opt/teamviewer/config/global.conf 2> /dev/null)
	if [ -z "$lic_accep" ];
	then	
		sleep 2
	else
		docker cp teamviewer:/opt/teamviewer/config/global.conf $HOME/teamv_cont
		break
	fi
done
# Criando Alias para iniciar container com um comando (caso ainda não criado)

if [ -z "$(grep 'dock_teamv' $HOME/.bashrc)" ];
then
	echo 'Criando alias para container, use o comando dock_teamv para iniciar o container'; sleep 2
	echo -e "\nalias dock_teamv='rm -r /tmp/containercookie; touch /tmp/containercookie; \
	Cookiefile=/tmp/containercookie \
	Cookie=\"\$(xauth nlist \$DISPLAY | sed -e 's/^..../ffff/')\" ; \
	echo \"\$Cookie\" | xauth -f \"\$Cookiefile\" nmerge -; \
	docker run -it --name teamviewer --env XAUTHORITY=/cookie --volume \$Cookiefile:/cookie --env DISPLAY=\$DISPLAY --volume /tmp/.X11-unix/X0:/tmp/.X11-unix/X0 -v \$HOME/teamv_cont/global.conf:/opt/teamviewer/config/global.conf --ipc=host ubu14/teamviewer;docker container prune -f; reset'" >> $HOME/.bashrc
	source $HOME/.bashrc; bash
fi
